### ISSUE TITLE
Redstone 0.5.18 method not found: 'isNotEmpty'

### ISSUE THREAD

**Issue by OzzieOrca** [redstone-dart/redstone.dart#44]
I upgraded to Dart 1.7 and Redstone 0.5.18 and am getting the following errors when running my Dart server. I'm not sure if this is something I'm doing wrong or if it is a bug but it worked fine on Redstone 0.5.16. I'd appreciate any suggestions you might have. Thanks!

```
SEVERE: 2014-10-15 23:21:09.135: Failed to configure handlers. - Closure call with mismatched arguments: function 'isNotEmpty'

NoSuchMethodError: method not found: 'isNotEmpty'
Receiver: Closure: () => List<String> from Function 'urlParameterNames':.
Arguments: []
Unhandled exception:
Uncaught Error: Closure call with mismatched arguments: function 'isNotEmpty'

NoSuchMethodError: method not found: 'isNotEmpty'
Receiver: Closure: () => List<String> from Function 'urlParameterNames':.
Arguments: []
Stack Trace:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#1      _configureTarget (package:redstone/src/setup_impl.dart:834:60)
#2      _configureGroup.<anonymous closure>.<anonymous closure> (package:redstone/src/setup_impl.dart:512:25)
#3      Object&ListMixin.forEach (dart:collection/list.dart:60)
#4      _configureGroup.<anonymous closure> (package:redstone/src/setup_impl.dart:484:28)
#5      IterableBase.forEach (dart:collection/iterable.dart:227)
#6      _configureGroup (package:redstone/src/setup_impl.dart:482:39)
#7      _scanHandlers.<anonymous closure> (package:redstone/src/setup_impl.dart:386:20)
#8      List.forEach (dart:core-patch/growable_array.dart:254)
#9      _scanHandlers (package:redstone/src/setup_impl.dart:376:17)
#10     setUp (package:redstone/server.dart:464:18)
#11     start.<anonymous closure> (package:redstone/server.dart:396:10)
#12     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#13     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:12)
#14     _handleTimeout (dart:io/timer_impl.dart:292)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:130)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:883)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:84)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:131)
```
